version: "3.6"

services:
  komiac:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: komiac-app
    restart: always
    depends_on:
      - postgres
    environment:
      - KOMIAC_DB_NAME=${KOMIAC_DB_NAME:-komiac}
      - KOMIAC_DB_PASS=${KOMIAC_DB_PASS:-password}
      - KOMIAC_DB_USER=${KOMIAC_DB_USER:-admin}
      - KOMIAC_DB_PORT=5432
      - KOMIAC_DB_HOST=postgres
      - KOMIAC_HOST=0.0.0.0
    ports:
      - "127.0.0.1:${KOMIAC_PORT:-8080}:80"

  postgres:
    image: postgres:12-alpine
    container_name: komiac-postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${KOMIAC_DB_PASS:-password}
      POSTGRES_USER: ${KOMIAC_DB_USER:-admin}
      POSTGRES_DB: ${KOMIAC_DB_NAME:-komiac}
    ports:
      - "127.0.0.1:${KOMIAC_DB_PORT:-5432}:5432"
    volumes:
      - ./postgresql-data:/var/lib/postgresql/data

  pgadmin:
    container_name: komiac-pgadmin
    image: dpage/pgadmin4:4
    restart: always
    privileged: true
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@nlt.net
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-password}
    ports:
      - ${PGADMIN_PORT:-5431}:80
