swagger: "2.0"

info:
  description: "microservice for komiac"
  title: komiac
  version: 1.3.0

basePath: /v1

consumes:
  - application/json

produces:
  - application/json

schemes:
  - http

definitions:
  error:
    type: object
    required:
      - message
    properties:
      message:
        type: string
  application:
    type: object
    properties:
      UUID:
        type: string
        format: uuid
      medicalOrganizationOID:
        type: string
      divisionOID:
        type: string
      year:
        type: integer
      SMNN:
        type: string
      MNN:
        type: string
      form:
        type: string
      dosage:
        type: string
      consumerUnit:
        type: string
      itemUnit:
        type: string
      privilegeProgramCode:
        type: string
      privilegeProgram:
        type: string
    required:
      - UUID
      - medicalOrganizationOID
      - divisionOID
      - year
      - SMNN
      - MNN
      - form
      - dosage
      - consumerUnit
      - itemUnit
      - privilegeProgramCode
      - privilegeProgram
  applications:
    type: array
    items:
      $ref: "#/definitions/application"


paths:
  /application:
    post:
      tags:
        - Application
      operationId: addList
      description: "Add new and update existing applications"
      parameters:
        - name: body
          in: body
          schema:
            $ref: "#/definitions/applications"
      responses:
        200:
          description: "Success"
        default:
          description: "Error"
          schema:
            $ref: "#/definitions/error"
    get:
      tags:
        - Application
      operationId: getList
      parameters:
        - name: divisionOID
          in: query
          type: string
          required: true
        - name: year
          in: query
          type: integer
          required: true
        - name: MNN
          in: query
          type: string
          required: true
      description: "Get applications by filters"
      responses:
        200:
          description: "Success"
          schema:
            $ref: "#/definitions/applications"
        default:
          description: "Error"
          schema:
            $ref: "#/definitions/error"

  /application/{uuid}:
    delete:
      tags:
        - Application
      operationId: delete
      description: "Delete application"
      parameters:
        - name: uuid
          in: path
          required: true
          type: string
          format: uuid
      responses:
        200:
          description: "Success"
        404:
          description: "Not Found"
          schema:
            $ref: "#/definitions/error"
        default:
          description: "Error"
          schema:
            $ref: "#/definitions/error"
