// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"bytes"
	"context"
	"encoding/json"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Medicament medicament
//
// swagger:model medicament
type Medicament struct {

	// m n n
	MNN string `json:"MNN,omitempty"`

	// s m n n
	SMNN string `json:"SMNN,omitempty"`

	// consumer unit
	ConsumerUnit string `json:"consumerUnit,omitempty"`

	// dosage
	Dosage string `json:"dosage,omitempty"`

	// form
	Form string `json:"form,omitempty"`
}

// UnmarshalJSON unmarshals this object while disallowing additional properties from JSON
func (m *Medicament) UnmarshalJSON(data []byte) error {
	var props struct {

		// m n n
		MNN string `json:"MNN,omitempty"`

		// s m n n
		SMNN string `json:"SMNN,omitempty"`

		// consumer unit
		ConsumerUnit string `json:"consumerUnit,omitempty"`

		// dosage
		Dosage string `json:"dosage,omitempty"`

		// form
		Form string `json:"form,omitempty"`
	}

	dec := json.NewDecoder(bytes.NewReader(data))
	dec.DisallowUnknownFields()
	if err := dec.Decode(&props); err != nil {
		return err
	}

	m.MNN = props.MNN
	m.SMNN = props.SMNN
	m.ConsumerUnit = props.ConsumerUnit
	m.Dosage = props.Dosage
	m.Form = props.Form
	return nil
}

// Validate validates this medicament
func (m *Medicament) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this medicament based on context it is used
func (m *Medicament) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Medicament) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Medicament) UnmarshalBinary(b []byte) error {
	var res Medicament
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
