// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "microservice for komiac",
    "title": "komiac",
    "version": "1.0.0"
  },
  "basePath": "/v1",
  "paths": {
    "/healthCheck": {
      "get": {
        "operationId": "healthCheck",
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "object",
              "properties": {
                "ok": {
                  "type": "boolean"
                }
              }
            }
          }
        }
      }
    }
  },
  "definitions": {
    "application": {
      "type": "object",
      "properties": {
        "customer": {
          "$ref": "#/definitions/customer"
        },
        "department": {
          "$ref": "#/definitions/department"
        },
        "medicaments": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/medicament"
          }
        },
        "mnemocode": {
          "type": "string"
        }
      }
    },
    "customer": {
      "type": "object",
      "properties": {
        "OID": {
          "type": "string"
        }
      }
    },
    "department": {
      "type": "object",
      "properties": {
        "OID": {
          "type": "string"
        }
      }
    },
    "error": {
      "type": "object",
      "required": [
        "message"
      ],
      "properties": {
        "message": {
          "type": "string"
        }
      }
    },
    "medicament": {
      "type": "object",
      "properties": {
        "MNN": {
          "type": "string"
        },
        "SMNN": {
          "type": "string"
        },
        "consumerUnit": {
          "type": "string"
        },
        "dosage": {
          "type": "string"
        },
        "form": {
          "type": "string"
        }
      }
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "microservice for komiac",
    "title": "komiac",
    "version": "1.0.0"
  },
  "basePath": "/v1",
  "paths": {
    "/healthCheck": {
      "get": {
        "operationId": "healthCheck",
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "object",
              "properties": {
                "ok": {
                  "type": "boolean"
                }
              }
            }
          }
        }
      }
    }
  },
  "definitions": {
    "application": {
      "type": "object",
      "properties": {
        "customer": {
          "$ref": "#/definitions/customer"
        },
        "department": {
          "$ref": "#/definitions/department"
        },
        "medicaments": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/medicament"
          }
        },
        "mnemocode": {
          "type": "string"
        }
      }
    },
    "customer": {
      "type": "object",
      "properties": {
        "OID": {
          "type": "string"
        }
      }
    },
    "department": {
      "type": "object",
      "properties": {
        "OID": {
          "type": "string"
        }
      }
    },
    "error": {
      "type": "object",
      "required": [
        "message"
      ],
      "properties": {
        "message": {
          "type": "string"
        }
      }
    },
    "medicament": {
      "type": "object",
      "properties": {
        "MNN": {
          "type": "string"
        },
        "SMNN": {
          "type": "string"
        },
        "consumerUnit": {
          "type": "string"
        },
        "dosage": {
          "type": "string"
        },
        "form": {
          "type": "string"
        }
      }
    }
  }
}`))
}
