// Code generated by go-swagger; DO NOT EDIT.

package application

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"

	"komiac/internal/api/restapi/models"
)

// GetListOKCode is the HTTP code returned for type GetListOK
const GetListOKCode int = 200

/*
GetListOK Success

swagger:response getListOK
*/
type GetListOK struct {

	/*
	  In: Body
	*/
	Payload models.Applications `json:"body,omitempty"`
}

// NewGetListOK creates GetListOK with default headers values
func NewGetListOK() *GetListOK {

	return &GetListOK{}
}

// WithPayload adds the payload to the get list o k response
func (o *GetListOK) WithPayload(payload models.Applications) *GetListOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get list o k response
func (o *GetListOK) SetPayload(payload models.Applications) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetListOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = models.Applications{}
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

func (o *GetListOK) GetListResponder() {}

/*
GetListDefault Error

swagger:response getListDefault
*/
type GetListDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetListDefault creates GetListDefault with default headers values
func NewGetListDefault(code int) *GetListDefault {
	if code <= 0 {
		code = 500
	}

	return &GetListDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get list default response
func (o *GetListDefault) WithStatusCode(code int) *GetListDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get list default response
func (o *GetListDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the get list default response
func (o *GetListDefault) WithPayload(payload *models.Error) *GetListDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get list default response
func (o *GetListDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetListDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

func (o *GetListDefault) GetListResponder() {}

type GetListNotImplementedResponder struct {
	middleware.Responder
}

func (*GetListNotImplementedResponder) GetListResponder() {}

func GetListNotImplemented() GetListResponder {
	return &GetListNotImplementedResponder{
		middleware.NotImplemented(
			"operation authentication.GetList has not yet been implemented",
		),
	}
}

type GetListResponder interface {
	middleware.Responder
	GetListResponder()
}
